---
title: "STAT423_Group_Project"
output: html_document
date: "2024-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(caret)
library(faraway)
```

```{r}
data <- read.csv("Health_insurance.csv")
```

```{r data_check}
head(data)
skimr::skim(data)
```
```{r}
data <- data %>%
  mutate(children = ifelse(children > 0, "have child", "no child"))
data$sex <- as.factor(data$sex)
data$smoker <- as.factor(data$smoker)
data$region <- as.factor(data$region)
```

```{r box-cox_transform}
# Box-Cox transformation
bc_transform <- boxcox(charges ~ ., data = data, lambda = seq(-2, 2, by=0.1))
title(main = "95% CI for the Box-Cox transform.")

# Log transformation
data$charges <- log(data$charges)
```

```{r data_split}
set.seed(423)

df_shuffled <- data[sample(nrow(data)), ]

n_total <- nrow(df_shuffled)
n_train <- floor(0.8 * n_total)

train_set <- df_shuffled[1:n_train, ]
test_set <- df_shuffled[(n_train + 1):n_total, ]
```

```{r}
plot(train_set)
```

```{r data_check_og}
par(mfrow=c(2,2))

hist(train_set$age, main="Age Distribution", xlab="Age")
hist(train_set$bmi, main="BMI Distribution", xlab="BMI")
hist(train_set$charges, main="Charges Distribution", xlab="Charges")
```
```{r lr_fit_initial}
fitfull <- lm(charges ~ ., data = train_set)
summary(fitfull)
```
```{r detailed_residual_plot}
par(mfrow=c(2, 2))

plot(fitfull,which=1)
plot(fitfull,which=2)
plot(fitfull,which=3)
plot(fitfull,which=4)
```
```{r}
datasmoker <- train_set %>% filter(smoker == "yes")
fit12 <- lm(charges ~ age+sex+bmi+children+region, data = datasmoker)
summary(fit12)
par(mfrow=c(2, 2))
plot(fit12,which=1)
plot(fit12,which=2)
plot(fit12,which=3)
plot(fit12,which=4)
```

```{r}
datanosmoker <- train_set %>% filter(smoker == "no")
fit13 <- lm(charges ~ age+sex+bmi+children+region, data = datanosmoker)
summary(fit13)
par(mfrow=c(2, 2))
plot(fit13,which=1)
plot(fit13,which=2)
plot(fit13,which=3)
plot(fit13,which=4)
```


######################################################################################



```{r smoker}
# check reasons for innormal
# irrelated to smoke
data_smoker <- data %>% filter(smoker == 2)

model <- lm(charges ~ ., data = data_smoker)

qqnorm(residuals(model))
qqline(residuals(model), col="red")

data_non_smoker <- data %>% filter(smoker == 1)

model <- lm(charges ~ ., data = data_non_smoker)

qqnorm(residuals(model))
qqline(residuals(model), col="red")
```

```{r bootstrap, warning=FALSE}
bootstrap_df <- function(data, n_bootstrap) {
  bootstrap_results <- list()
  
  for (i in 1:n_bootstrap) {
    sample_data <- data %>% sample_n(size = nrow(data), replace = TRUE)
    bootstrap_results[[i]] <- summarise_all(sample_data, mean)
  }
  
  do.call(rbind, bootstrap_results)
}

n_bootstrap <- 1000 # number of n

bootstrap_results <- bootstrap_df(data, n_bootstrap)
```

```{r data_check_bootstrap}
par(mfrow=c(2,2))

hist(bootstrap_results$age, main="Age Distribution", xlab="Age")
hist(bootstrap_results$bmi, main="BMI Distribution", xlab="BMI")
hist(bootstrap_results$children, main="Children Distribution", xlab="Children")
hist(bootstrap_results$charges, main="Charges Distribution", xlab="Charges")
```

```{r data_check_og}
par(mfrow=c(2,2))

hist(data$age, main="Age Distribution", xlab="Age")
hist(data$bmi, main="BMI Distribution", xlab="BMI")
hist(data$children, main="Children Distribution", xlab="Children")
hist(data$charges, main="Charges Distribution", xlab="Charges")
```

```{r children_count}
data %>%
  group_by(children) %>%
  count()
```

```{r lr_fit_initial}
fit1 <- lm(charges ~ ., data = data)
summary(fit1)
```

```{r box-cox_transform}
# Box-Cox transformation
bc_transform <- boxcox(charges ~ ., data = data, lambda = seq(-2, 2, by=0.1))
title(main = "95% CI for the Box-Cox transform.")

# Log transformation
data$charges <- log(data$charges)
```

```{r corrplot}
library(corrplot)

cor_matrix <- cor(data[-7])
corrplot(cor_matrix, method = "circle")
```

```{r data_split}
set.seed(423)

df_shuffled <- bootstrap_results[sample(nrow(bootstrap_results)), ]

n_total <- nrow(df_shuffled)
n_train <- floor(0.8 * n_total)

train_set <- df_shuffled[1:n_train, ]
test_set <- df_shuffled[(n_train + 1):n_total, ]
```

```{r boot_strap_fit}
model <- lm(charges ~ ., data = train_set)
summary(model)
```

```{r res_qq_plot}
hist(residuals(model), main="Histogram of Residuals", xlab="Residuals", breaks=30)
qqnorm(residuals(model))
qqline(residuals(model), col="red")
```

```{r detailed_residual_plot}
par(mfrow=c(2, 2))

plot(model,which=1)
plot(model,which=2)
plot(model,which=3)
plot(model,which=4)
```

```{r model_selection}
best_subset_fit <- regsubsets(charges ~ ., data = train_set)
best_subset_summary <- summary(best_subset_fit)

bic <- best_subset_summary$bic
cp <- best_subset_summary$cp

best_bic <- which.min(bic)
best_cp <- which.min(cp)

best_subset_summary$which[best_bic, ]
best_subset_summary$which[best_cp, ]
```

```{r selected_model}
selected_model <- lm(charges ~ age+bmi+smoker, data = train_set)
summary(selected_model)
```

```{r backward}
fit1 <- lm(charges~., data=train_set, x=TRUE, y=TRUE)
step(fit1, dir="backward")
```

```{r forward}
fit.empty <- lm(charges~1,data=train_set)
step(fit.empty, dir="forward", scope=list(upper=fit1,lowwer=fit.empty))
```

```{r bi-directional}
fit2 <- lm(charges~smoker + age + bmi + children + sex, data = train_set, x=TRUE, y=TRUE)
step(fit1, dir="both", k=2)
```

```{r selected_model_1}
selected_model <- lm(charges ~ age + sex + bmi + children + smoker, data = train_set, x=TRUE, y=TRUE)
summary(selected_model)
```
